import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img />
          <Link legacyBehavior href="/" passHref>
            <a>Home</a>
          </Link>
          <Link legacyBehavior href="/about-us" passHref>
            <a>About Us</a>
          </Link>
          <Link legacyBehavior href="/events" passHref>
            <a>Events</a>
          </Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => (
          <Link legacyBehavior key={ev.id} href={`/events/${ev.id}`} passHref>
            <a>
              <Image src={ev.image} alt={ev.title} width={200} height={300} />{" "}
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            </a>
          </Link>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>footer that is very likely order</p>
      </footer>
    </div>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
